version: '2'

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - loki-net

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/var/log/spring-pet-clinic
    networks:
      - loki-net

  petclinic:
    image: pet-clinic-monitor
    ports:
      - "8080:8080"
    networks:
      - loki-net
    depends_on:
      - loki

networks:
  loki-net: